# pytest ./tests/behavioral_test.py
# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.edge.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestFinaltestingactual():
    def setup_method(self, method):
        options = Options()
        options.add_argument("--disable-popup-blocking")
        options.add_argument("--start-maximized")
        self.driver = webdriver.Edge(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_finaltestingactual(self):
        # Navigate to the login page
        self.driver.get("http://127.0.0.1:5000/login")
        self.driver.set_window_size(1920, 1080)

        # Login as 'pm' with password '123456789'
        self.driver.find_element(By.NAME, "username").send_keys("pm")
        self.driver.find_element(By.NAME, "password").send_keys("123456789")
        time.sleep(2)
        self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)



        # Wait for the sidebar to load
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.ID, "sidebar"))
        )

        # Click on "Add a New Jobsite" in the sidebar
        self.driver.find_element(By.LINK_TEXT, "Add New Jobsite").click()

        self.driver.find_element(By.ID, "nameInput").send_keys("Test Project")
        time.sleep(2)
        self.driver.find_element(By.ID, "descriptionInput").send_keys("Test Description")
        time.sleep(2)
        self.driver.find_element(By.ID, "latForm").send_keys("35.2271")
        time.sleep(2)
        self.driver.find_element(By.ID, "lngForm").send_keys("-80.8431")
        time.sleep(2)
        self.driver.find_element(By.ID, "radiusForm").send_keys("500")
        time.sleep(2)

        # Submit the form
        self.driver.find_element(By.ID, "submitButton").click()

        # End the test
        time.sleep(2)
